name: Test

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v4

    - uses: actions/setup-go@v5
      with:
        go-version: '1.22'
        cache: false

    - name: Lint
      uses: golangci/golangci-lint-action@v5
      with:
        working-directory: server

    - name: Test
      run: make test
