name: Test

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v4

    - uses: actions/setup-go@v5
      with:
        go-version: '1.24'
        cache: false

    - name: Lint
      run: make lint

    - name: Test
      run: make test
